name: pawtrace_app
description: PetTrace - Community-driven pet protection and recovery app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Date & Localization
  intl: ^0.19.0

  # UI & Fonts
  google_fonts: ^6.2.1

  # Maps
  google_maps_flutter: ^2.9.0

  # Camera & Image
  image_picker: ^1.1.2
  camera: ^0.11.0+2

  # Image processing for AI
  image: ^4.1.7

  # Charts
  fl_chart: ^0.69.0

  # Backend & Auth
  supabase_flutter: ^2.6.0
  responsive_framework: ^1.5.1
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  http: ^1.2.0
  http_parser: ^4.0.2
  url_launcher: ^6.3.2

  # Excel export
  excel: ^4.0.6
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  google_mlkit_text_recognition: 0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
